# Generated by Django 5.1.4 on 2025-05-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('source_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('intermediate_stops', models.TextField(help_text='List of intermediate stops, separated by commas.')),
                ('train_type', models.CharField(max_length=50)),
                ('seat_classes', models.JSONField()),
                ('total_seats', models.IntegerField()),
                ('fare', models.JSONField()),
                ('train_status', models.BooleanField(default=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
