# Generated by Django 5.1.4 on 2025-05-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='train',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='train',
            name='fare_normal',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='train',
            name='fare_tatkal',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='train',
            name='total_distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='total_seats_ac1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='total_seats_ac2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='total_seats_sleeper',
            field=models.IntegerField(default=0),
        ),
    ]
