# Generated by Django 5.1.4 on 2025-05-13 05:40

import django.db.models.deletion
import ticket_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_remove_train_fare_remove_train_total_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(default=ticket_app.models.generate_pnr, editable=False, max_length=6)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.PositiveIntegerField()),
                ('passenger_gender', models.CharField(max_length=10)),
                ('seat_class', models.CharField(max_length=20)),
                ('booking_type', models.CharField(choices=[('Normal', 'Normal'), ('Tatkal', 'Tatkal')], max_length=10)),
                ('boarding_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ticket_app.train')),
            ],
        ),
    ]
