# Generated by Django 5.1.4 on 2025-05-13 05:43

import ticket_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(default=ticket_app.models.generate_pnr, editable=False, max_length=8),
        ),
    ]
