# Generated by Django 5.1.4 on 2025-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_alter_booking_pnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
