# Generated by Django 5.1.4 on 2025-05-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0006_booking_seat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(max_length=20)),
                ('total_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField(default=0)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_availability', to='ticket_app.train')),
            ],
            options={
                'unique_together': {('train', 'seat_class')},
            },
        ),
    ]
