# Generated by Django 5.1.4 on 2025-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0008_delete_seatavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
