# Generated by Django 5.1.4 on 2025-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_alter_booking_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='available_seats_ac1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='available_seats_ac2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='available_seats_sleeper',
            field=models.IntegerField(default=0),
        ),
    ]
