# Generated by Django 5.1.4 on 2025-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0010_train_available_seats_ac1_train_available_seats_ac2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='intermediate_stops',
            field=models.JSONField(default=list),
        ),
    ]
