# Generated by Django 5.1.4 on 2025-05-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0011_alter_train_intermediate_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='wants_pantry',
            field=models.BooleanField(default=False),
        ),
    ]
