# Generated by Django 5.1.4 on 2025-05-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0013_pantryitem_bookingpantry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='wants_pantry',
            new_name='meal',
        ),
    ]
