# Generated by Django 5.1.4 on 2025-05-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0014_rename_wants_pantry_booking_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpantry',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.booking'),
        ),
    ]
